/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-26 04:38:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/souravsharma/Documents/WorkNest/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WorkNestApp/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308107170000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1308152200000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<title>WorkNest</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	margin: 0;\n");
      out.write("	min-height: 100vh;\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("	font-family: 'Poppins', sans-serif;\n");
      out.write("	background: linear-gradient(135deg, #f6f3fa, #ebe3f8);\n");
      out.write("	color: #4b4453;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	align-items: center;\n");
      out.write("	background: #a88fd8;\n");
      out.write("	padding: 1rem 2rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav .title {\n");
      out.write("	font-size: 1.6rem;\n");
      out.write("	font-weight: 700;\n");
      out.write("	color: white;\n");
      out.write("	letter-spacing: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav .actions {\n");
      out.write("	display: flex;\n");
      out.write("	gap: 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav .actions a {\n");
      out.write("	padding: 0.6rem 1.2rem;\n");
      out.write("	border-radius: 30px;\n");
      out.write("	background: white;\n");
      out.write("	color: #6a4ba8;\n");
      out.write("	font-weight: 600;\n");
      out.write("	text-decoration: none;\n");
      out.write("	transition: all 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav .actions a:hover {\n");
      out.write("	background: #d3c2f7;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero {\n");
      out.write("	text-align: center;\n");
      out.write("	padding: 2rem 1rem;\n");
      out.write("	background: linear-gradient(135deg, #d3c2f7, #f1ebfc);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero h1 {\n");
      out.write("	font-size: 2rem;\n");
      out.write("	margin-bottom: 0.5rem;\n");
      out.write("	background: linear-gradient(to right, #6a4ba8, #a88fd8);\n");
      out.write("	-webkit-background-clip: text;\n");
      out.write("	-webkit-text-fill-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero p {\n");
      out.write("	font-size: 1rem;\n");
      out.write("	color: #5a5270;\n");
      out.write("	max-width: 600px;\n");
      out.write("	margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("	flex-grow: 1;\n");
      out.write("	max-width: 1000px;\n");
      out.write("	margin: 2rem auto;\n");
      out.write("	padding: 0 1.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card {\n");
      out.write("	background: white;\n");
      out.write("	padding: 2rem;\n");
      out.write("	border-radius: 1.5rem;\n");
      out.write("	box-shadow: 0 6px 16px rgba(168, 143, 216, 0.25);\n");
      out.write("	transition: transform 0.3s, box-shadow 0.3s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card:hover {\n");
      out.write("	transform: translateY(-6px);\n");
      out.write("	box-shadow: 0 10px 22px rgba(168, 143, 216, 0.35);\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer {\n");
      out.write("	background: #a88fd8;\n");
      out.write("	color: white;\n");
      out.write("	padding: 1rem;\n");
      out.write("	text-align: center;\n");
      out.write("	border-top-left-radius: 1rem;\n");
      out.write("	border-top-right-radius: 1rem;\n");
      out.write("	margin-top: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn {\n");
      out.write("	display: inline-block;\n");
      out.write("	padding: 0.7rem 1.5rem;\n");
      out.write("	border-radius: 50px;\n");
      out.write("	background: linear-gradient(135deg, #a88fd8, #6a4ba8);\n");
      out.write("	color: white;\n");
      out.write("	font-weight: 600;\n");
      out.write("	text-decoration: none;\n");
      out.write("	transition: all 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn:hover {\n");
      out.write("	box-shadow: 0 6px 16px rgba(168, 143, 216, 0.4);\n");
      out.write("	transform: translateY(-2px);\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<nav>\n");
      out.write("		<div class=\"title\">WorkNest</div>\n");
      out.write("		<div class=\"actions\">\n");
      out.write("			<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">Admin</a> <a\n");
      out.write("				href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">User</a>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<div class=\"hero\">\n");
      out.write("		<h1>Welcome to WorkNest</h1>\n");
      out.write("		<p>A calm lavender workspace where productivity meets elegance.</p>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"container\">\n");
      out.write("\n");
      out.write("		");
      out.write("\n");
      out.write("		<div class=\"container my-4\">\n");
      out.write("\n");
      out.write("			<div class=\"row justify-content-center\">\n");
      out.write("				<div class=\"col-md-6\">\n");
      out.write("					<div class=\"card shadow-sm\">\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<h3 class=\"mb-3\">Admin Register</h3>\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							<form method=\"post\" action=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("								<div class=\"mb-3\">\n");
      out.write("									<label>Name</label><input name=\"name\" class=\"form-control\"\n");
      out.write("										required>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"mb-3\">\n");
      out.write("									<label>Email</label><input name=\"email\" type=\"email\"\n");
      out.write("										class=\"form-control\" required>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"mb-3\">\n");
      out.write("									<label>Password</label><input name=\"password\" type=\"password\"\n");
      out.write("										class=\"form-control\" required>\n");
      out.write("								</div>\n");
      out.write("								<button class=\"btn btn-success\">Register</button>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<footer>© 2025 WorkNest</footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/admin-register.jsp(128,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/admin/login");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/jsp/admin-register.jsp(129,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/user/login");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/admin-register.jsp(159,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("								<div class=\"alert alert-danger\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\n");
        out.write("							");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/jsp/admin-register.jsp(162,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/admin/register");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }
}
